# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-18 16:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='email',
            new_name='email_address',
        ),
    ]
