# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-18 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20190318_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='employee_unique_id',
        ),
        migrations.AddField(
            model_name='employees',
            name='employee_id',
            field=models.CharField(default='7584965894', max_length=10),
        ),
    ]
