# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-20 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20190318_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='email_address',
            field=models.EmailField(max_length=60),
        ),
        migrations.AlterField(
            model_name='employees',
            name='employee_id',
            field=models.CharField(max_length=10),
        ),
    ]
