# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-16 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_auto_20180228_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='activated',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='added',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='age',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='country',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='deduction',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='deduction_description',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='earning',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='earning_description',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='national_identifier',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='place_of_birth',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='position',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='salary',
        ),
        migrations.AddField(
            model_name='employees',
            name='department',
            field=models.CharField(default='finance', max_length=25),
        ),
        migrations.AddField(
            model_name='employees',
            name='employee_unique_id',
            field=models.CharField(default='MD12S1', max_length=10),
        ),
        migrations.AddField(
            model_name='employees',
            name='phone_number',
            field=models.IntegerField(default='+254'),
        ),
        migrations.DeleteModel(
            name='Relationship',
        ),
    ]
