# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-16 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_auto_20190316_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='department',
            field=models.CharField(choices=[('FINANCE', 'FINANCE'), ('HR', 'HR'), ('MARKETING', 'MARKETING'), ('OPERATIONS', 'OPERATIONS'), ('R%D', 'R%D')], max_length=25),
        ),
        migrations.AlterField(
            model_name='employees',
            name='employee_unique_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='employees',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
