# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-16 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_auto_20190316_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='email',
            field=models.EmailField(default='@gmail.com', max_length=60),
        ),
        migrations.AlterField(
            model_name='employees',
            name='phone_number',
            field=models.PositiveIntegerField(),
        ),
    ]
