# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-17 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_auto_20190317_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='freeze',
        ),
        migrations.AlterField(
            model_name='employees',
            name='department',
            field=models.CharField(choices=[('employee', 'employee'), ('FINANCE', 'FINANCE'), ('HR', 'HR'), ('MARKETING', 'MARKETING'), ('OPERATIONS', 'OPERATIONS'), ('R%D', 'R%D')], max_length=25),
        ),
    ]
