# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-17 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_auto_20190317_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='contract',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='first_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='employees',
            name='last_name',
            field=models.CharField(max_length=60),
        ),
    ]
